apiVersion: v1
kind: Service
metadata:
  name: platformservice-srv
spec:
  type: NodePort
  selector:
    app: platformserviceapi
  ports:
  - name: platformservice-srv
    protocol: TCP
    port: 80
    targetPort: 80

